### PR TITLE
Pullrequest for Issue #7

### PR DESCRIPTION
**Pull request by sbiermann**
I have added support for multiple Eventbinder with different RabbitMQ connections. And i have also added a way to register the connection listener in the binder configuration, we need that for our internal monitoring of the applications.

---
This change is [Reviewable](https://reviewable.io/reviews/reinhapa/rabbitmq-cdi/8)

### CODE REVIEW

**Comment by sbiermann** [comment]
No, that doesn't work. It was my first test be removing the Singleton Annotation to make it dependent. It doesn't work because the EventPublisher is a Singleton and the first existing or new ConnectionProducer will be injected in the constructor. And you need a different ConnectionProducer for each Connection to another vHost or Host.

**Comment by reinhapa** [comment]
@sbiermann I created a new version that at least in my test supports multiple binders. You may check this version out.

**Comment by sbiermann** [comment]
Due time constraints we needed a solution for going forward with our development, so we used our pull request code to build a special version for our local artifactory maven repository. That works perfectly for us, including the registration of own connection listener.

**Comment by reinhapa** [comment]
@sbiermann no problem. It would be great to get feedback for the latest version as soon you got time to test that in your environment.

**Pull request closed without merging**
