### PR TITLE
Added Support for dynamic basic properties

### PR DESCRIPTION
**Pull request by Gr33nbl00d**
Added support for dynamic basic properties, based on event information. Also allows to modify header values on the fly. To fill header data with data from event.

---
This change is [Reviewable](https://reviewable.io/reviews/reinhapa/rabbitmq-cdi/172)

### CODE REVIEW

**Comment by Gr33nbl00d** [comment]
This commit is the code to enhancement #148

**Comment by Gr33nbl00d** [comment]
Regarding the codacy issue in EventBinder i would not like to change the method access modifiert to anything else than package private. Because all other getter methods here are also package private. And for me package private is totally correct here as it should only be used internal by other classes in the same package. No possibility to override the method and not public accessible.

**Comment by Gr33nbl00d** [comment]
I have not forgotten this requets :) currently im under heavy load because of end of year business. But i will fix this as soon as possible

**Comment by Gr33nbl00d** [comment]
I can not figure out what the problem with the license is in basicpropertiescalculator class

**Comment by Gr33nbl00d** [comment]
Will you merge this? I have plenty of pull requests left for merging ;)

**Comment by Gr33nbl00d** [comment]
I think all should be fine now except review from you

**Comment by reinhapa** [comment]
LGTM

**Review by reinhapa — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 8 files at r1, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/reinhapa/rabbitmq-cdi/172#-:-MOFVrGLEvQjZtkF0sL7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
